adds url validation step

diff --git a/download b/download
--- a/download
+++ b/download
@@ -5,29 +5,34 @@
 
 ./deps curl
 
-url="$1" && shift || { echo "Usage: ./bare download URL [OUTPUT]"; exit 1; }
+[[ -t 0 ]] && { url=$1; shift; } || url=$(cat)
 
-[ "$(./bare youtube id "$url")" = 'Invalid YouTube URL' ] && is_youtube=0 || is_youtube=1
+[[ -z $url ]] && echo "No URL provided" && exit 1
 
+[[ $(validate url "$url") == 'false' ]] && echo "Invalid URL" && exit 1
+
+# check if this is a YouTube link
+[[ "$(./bare youtube id "$url")" = 'Invalid YouTube URL' ]] && is_youtube=0 || is_youtube=1
+
+# setup environment
 output_name="$(./bare random string 32)"
 temp_file=".var/downloads/${output_name}"
 
-while [ "$#" -gt 0 ]; do
-  case "$1" in
+while true; do # continue through remaining args
+  case $1 in
+	'') break ;;
 	--mp3) as_mp3=1 && shift ;;
 	--thumbnail) as_thumbnail=1 && shift ;;
-	--title) title="$2" && shift 2 ;;
-	--description) description="$2" && shift 2 ;;
-	--tags) tags="$2" && shift 2 ;;
 	* ) echo "Unknown option: $1" && exit 1 ;;
   esac
 done
 
-if [ "$is_youtube" = 1 ]; then
+if [[ "$is_youtube" = 1 ]]; then
 
-	[ "$as_mp3" ] && ./bare youtube download "$url" --mp3 && exit 0
-	[ "$as_thumbnail" ] && ./bare youtube download "$url" --thumbnail --max && exit 0
-	./bare youtube download "$url" && exit 0
+	[[ "$as_mp3" ]] && ./bare youtube download "$url" --mp3 && exit 0
+	[[ "$as_thumbnail" ]] && ./bare youtube download "$url" --thumbnail --max && exit 0
+	./bare youtube download "$url"
+	exit 0
 
 else
 
@@ -56,10 +61,7 @@ else
 
 	extension="${mime_extension_map[$mime_type]}"
 
-	if [ -z "$extension" ]; then
-	echo "Unsupported MIME type: $mime_type"
-	exit 1
-	fi
+	[[ -z "$extension" ]] && echo "Unsupported MIME type: $mime_type" && exit 1
 
 	# Construct the final output file name with the correct extension
 	output_file=".var/downloads/${output_name}.${extension}"
