adds rounding, up and down

diff --git a/math b/math
--- a/math
+++ b/math
@@ -1,11 +1,74 @@
 #!/usr/bin/env bash
 
-# delegate all math related problems in $1 to perl
+source .lib/barerc
 
-math_operation="$*"
-safe_math_operation=$(perl -e "print \"$math_operation\" =~ s/[^0-9+\-.*\/()]//gr")
+function main() {
 
-# Evaluate the sanitized math operation
-result=$(perl -e "print eval \"$safe_math_operation\"")
+	local operation
+	local expression
+	local output
 
-echo $result
+	remaining_args=() && while [[ $# -gt 0 ]]; do
+		case $1 in
+			round|floor|ceiling|ceil) operation=$1 && shift ;;
+			*) remaining_args+=("$1") && shift ;;
+		esac
+	done && set -- "${remaining_args[@]}"
+
+	case $operation in
+
+		round)
+
+			number=$1
+			decimals=${2:-0}
+			shift 2
+
+			[[
+				$(validate number "$number") == 'false'
+				||
+				$(validate number "$decimals") == 'false'
+			]] && echo "Error: invalid number" && exit 1
+
+			output=$(php -r "echo number_format($number, $decimals, '.', '');")
+
+			;;
+
+		floor)
+
+			number=$1
+			shift
+
+			[[ $(validate number "$number") == 'false' ]] && echo "Error: invalid number" && exit 1
+
+			output=$(php -r "echo floor($number);")
+
+			;;
+
+		ceil|ceiling)
+
+			number=$1
+			shift
+
+			[[ $(validate number "$number") == 'false' ]] && echo "Error: invalid number" && exit 1
+
+			output=$(php -r "echo ceil($number);")
+
+			;;
+
+		*)
+
+			# Concatenate all arguments into a single string
+			expression="$*"
+
+			# Use PHP to sanitize and evaluate the math operation
+			output=$(php -r "\$math_operation = '$expression'; if (preg_match('/^[0-9+\-.*\/() ]+$/', \$math_operation)) { echo eval('return ' . \$math_operation . ';'); } else { echo 'Invalid input'; }")
+
+			;;
+
+	esac
+
+	echo "$output" && exit 0
+
+}
+
+run_script "$@"
