- adds some new scripts - begins functional refactor project

diff --git a/.lib/setup b/.lib/setup
--- a/.lib/setup
+++ b/.lib/setup
@@ -9,15 +9,6 @@
 	RESET=$'\e[0m'
 }
 
-# Detect the platform (Linux or macOS)
-OS=""
-if [[ "$OSTYPE" == "linux-gnu"* ]]; then
-    OS="Linux"
-elif [[ "$OSTYPE" == "darwin"* ]]; then
-    OS="macOS"
-fi
-sleep 0.05
-
 # Function to check if everything is set up
 check_setup() {
     echo -e " ${GRAY}|${RESET} ${BLUE}Checking current setup...${RESET}"
@@ -67,33 +58,29 @@ prompt_secret() {
     sleep 0.05
 }
 
-touch .var/sync
-touch .etc/barerc
-touch .var/sync
-touch .var/bare.rec
+bash .lib/sync
 
 # Required variables
 required_variables=("OPENAI_API_KEY" "POSTMARK_API_TOKEN" "BARE_EMAIL_FROM" "STRIPE_SECRET_KEY" "EDITOR")
 
 # List of dependencies and their associated commands
 declare -A dependencies=(
-    ["curl"]="curl"
     ["jq"]="jq"
+    ["yq"]="yq"
+	["yt-dlp"]="yt-dlp"
+	["curl"]="curl"
+    ["ffmpeg"]="ffmpeg"
     ["recutils"]="recsel"
     ["sqlite3"]="sqlite3"
     ["pandoc"]="pandoc"
-    ["yq"]="yq"
     ["xxd"]="xxd"
     ["php"]="php"
     ["awk"]="awk"
     ["perl"]="perl"
     ["openssl"]="openssl"
     ["imagemagick"]="convert"
-    ["ffmpeg"]="ffmpeg"
     ["qrencode"]="qrencode"
-    ["yt-dlp"]="yt-dlp"
     ["csvkit"]="csvcut"
-    ["sqlpage"]="sqlpage"
 )
 
 # Main setup process
@@ -110,9 +97,7 @@ setup() {
     # Ensure required variables are set
     for var in "${required_variables[@]}"; do
         if ! grep -q "^export $var=" .etc/barerc; then
-
             echo -e " ${GRAY}|${RESET} ${YELLOW}Notice:${RESET} ${GREEN}$var${RESET} is not set."
-
             read -rp " ${GRAY}|${RESET} Set ${GREEN}$var${RESET} now? (y/n): " response
             sleep 0.05
             if [[ $response =~ ^[Yy]$ ]]; then
@@ -127,18 +112,54 @@ setup() {
     echo -e " ${GRAY}|${RESET} ${BLUE}Checking dependencies...${RESET}"
     sleep 0.05
 
-    # Check and install dependencies if needed
-    for package in "${!dependencies[@]}"; do
-        command=${dependencies[$package]}
 
-		if ! command -v "$command" >/dev/null 2>&1; then
-			echo -e " ${GRAY}|${RESET} ${YELLOW}$command missing.${RESET}"
-			read -rp " ${GRAY}|${RESET} Install '$package'? (y/n): " response
+
+
+    # Install dependencies based on OS
+
+    if [[ "$OS" == "Ubuntu" ]]; then
+
+		# Ubuntu
+
+		# make sure we have snap, and put snap in path
+		if ! command -v snap >/dev/null 2>&1; then
+			echo -e " ${GRAY}|${RESET} ${YELLOW}snap missing.${RESET}"
+			read -rp " ${GRAY}|${RESET} Install 'snap'? (y/n): " response
 			sleep 0.05
 			if [[ $response =~ ^[Yy]$ ]]; then
-				echo -e " ${GRAY}|${RESET} ${BLUE}Installing $package...${RESET}"
+				echo -e " ${GRAY}|${RESET} ${BLUE}Installing snap...${RESET}"
 				sleep 0.05
-				if [[ "$OS" == "Linux" ]]; then
+				sudo apt-get install -y snapd
+			fi
+		fi
+
+		if ! echo "$PATH" | grep -q "^/snap/bin"; then
+			# shellcheck disable=SC2016
+			echo 'export PATH=/snap/bin:$(echo "$PATH" | sed -e "s|/snap/bin:||g")' >> ~/.bashrc
+		fi
+
+		# we'll also need pipx
+		if ! command -v pipx >/dev/null 2>&1; then
+			echo -e " ${GRAY}|${RESET} ${YELLOW}pipx missing.${RESET}"
+			read -rp " ${GRAY}|${RESET} Install 'pipx'? (y/n): " response
+			sleep 0.05
+			if [[ $response =~ ^[Yy]$ ]]; then
+				echo -e " ${GRAY}|${RESET} ${BLUE}Installing pipx...${RESET}"
+				sleep 0.05
+				python3 -m pip install --user pipx
+				python3 -m pipx ensurepath
+			fi
+		fi
+
+		for package in "${!dependencies[@]}"; do
+			command=${dependencies[$package]}
+			if ! command -v "$command" >/dev/null 2>&1; then
+				echo -e " ${GRAY}|${RESET} ${YELLOW}$command missing.${RESET}"
+				read -rp " ${GRAY}|${RESET} Install '$package'? (y/n): " response
+				sleep 0.05
+				if [[ $response =~ ^[Yy]$ ]]; then
+					echo -e " ${GRAY}|${RESET} ${BLUE}Installing $package...${RESET}"
+					sleep 0.05
 					if [[ "$package" == "sqlpage" ]]; then
 						curl -sL -o sqlpage-linux.tgz \
 							https://github.com/lovasoa/SQLpage/releases/download/v0.26.0/sqlpage-linux.tgz
@@ -154,12 +175,33 @@ setup() {
 						curl_version=$(curl --version | head -n1 | awk '{print $2}')
 						if dpkg --compare-versions "$curl_version" lt 7.82; then
 							sudo snap install curl
-							echo "alias curl='/snap/bin/curl'" >> .var/barerc
 						fi
+					elif [[ "$package" == 'yt-dlp' ]]; then
+						pipx install yt-dlp
 					else
 						sudo apt-get install -y "$package" || echo -e " ${GRAY}|${RESET} ${YELLOW}Install $package manually.${RESET}"
 					fi
-				elif [[ "$OS" == "macOS" ]]; then
+					sleep 0.05
+				fi
+			else
+				echo -e " ${GRAY}|${RESET} ${GREEN}$command found.${RESET}"
+			fi
+			sleep 0.05
+		done
+
+    elif [[ "$OS" == "macOS" ]]; then
+
+		# macOS
+
+		for package in "${!dependencies[@]}"; do
+			command=${dependencies[$package]}
+			if ! command -v "$command" >/dev/null 2>&1; then
+				echo -e " ${GRAY}|${RESET} ${YELLOW}$command missing.${RESET}"
+				read -rp " ${GRAY}|${RESET} Install '$package'? (y/n): " response
+				sleep 0.05
+				if [[ $response =~ ^[Yy]$ ]]; then
+					echo -e " ${GRAY}|${RESET} ${BLUE}Installing $package...${RESET}"
+					sleep 0.05
 					if ! command -v brew >/dev/null 2>&1; then
 						echo -e " ${GRAY}|${RESET} ${YELLOW}Homebrew not found.${RESET}"
 						echo -e " ${GRAY}|${RESET} ${BLUE}Installing Homebrew...${RESET}"
@@ -170,18 +212,14 @@ setup() {
 					fi
 					brew install "$package" || echo -e " ${GRAY}|${RESET} ${YELLOW}Install $package manually.${RESET}"
 				fi
-				sleep 0.05
+			else
+				echo -e " ${GRAY}|${RESET} ${GREEN}$command found.${RESET}"
 			fi
-		else
-			echo -e " ${GRAY}|${RESET} ${GREEN}$command found.${RESET}"
-		fi
-        sleep 0.05
-    done
+			sleep 0.05
+		done
 
-	# do one more check if os is mac for coreutils (if gdate is missing)
-	if [[ "$OS" == "macOS" ]]; then
+		# Ensure coreutils is installed for gdate
 		if ! command -v gdate >/dev/null 2>&1; then
-
 			echo -e " ${GRAY}|${RESET} ${YELLOW}gdate missing.${RESET}"
 			read -rp " ${GRAY}|${RESET} Install 'coreutils'? (y/n): " response
 			sleep 0.05
@@ -190,54 +228,80 @@ setup() {
 				sleep 0.05
 				brew install coreutils
 			fi
-
 		fi
-	fi
 
-	# Determine the current shell and set the shell config file
-	if [ -n "$ZSH_VERSION" ]; then
-    	SHELL_CONFIG="$HOME/.zshrc"
-	elif [ -n "$BASH_VERSION" ]; then
-		if [ -f "$HOME/.bashrc" ]; then
-			SHELL_CONFIG="$HOME/.bashrc"
+	else
+
+		message="bare is designed for use with Ubuntu or macOS. If you're using a unix-like operating system, you'll probably be fine, but please install the required dependencies manually."
+		
+		if command -v fold > /dev/null && command -v column > /dev/null; then
+			echo "$message" | fold -s -w 60 | column -t
 		else
-			SHELL_CONFIG="$HOME/.bash_profile"
+			echo "$message"
+		fi
+
+    fi
+
+	# Minimum Bash version
+	required_version="5.1"
+	current_version=$(echo "$BASH_VERSION" | sed -E 's/^([0-9]+\.[0-9]+).*/\1/')
+
+	if [[ $OS = 'macOS' ]]; then
+		deps brew
+		# Check that we have at least Bash 5.1+
+		if [[ $(perl -e "print 1 if '$current_version' ge '$required_version'") != 1 ]]; then
+			echo "Error: Bash version 5.1+ required. Currently running $current_version."
+			echo "To install Bash 5.1+, run the following command:"
+			echo "  brew install bash"
+			echo "Ensure that Homebrew's bin directory is in your PATH:"
+			echo "  export PATH=\"/opt/homebrew/bin:\$PATH\"  # For Apple Silicon (M1+)"
+			echo "  export PATH=\"/usr/local/bin:\$PATH\"    # For Intel Macs"
+			exit 1
+		fi
+	elif [[ $OS == 'Ubuntu' ]]; then
+		deps snap
+		# Check that we have at least Bash 5.1+
+		if [[ $(perl -e "print 1 if '$current_version' ge '$required_version'") != 1 ]]; then
+			echo "Error: Bash version 5.1+ required. Currently running $current_version."
+			echo "To install Bash 5.1+, run the following command:"
+			echo "  sudo snap refresh && sudo snap install bash"
+			exit 1
 		fi
 	else
-		SHELL_CONFIG="$HOME/.profile"
+		echo "☝️ Please make sure you're using Bash 5.1+ to use bare."
 	fi
-	
-	# Final message
-	echo ""
-	echo -e " ${GRAY}|${RESET} ${GREEN}Setup complete! 🎉${RESET}"
-	echo ""
-	
-	# Define the alias string
-	ALIAS_STRING="alias bare='$BARE_DIR/bare'"
+    
+    # Final message
+    echo ""
+    echo -e " ${GRAY}|${RESET} ${GREEN}Setup complete! 🎉${RESET}"
+    echo ""
+    
+    # Define the alias string
+    ALIAS_STRING="alias bare='$BARE_DIR/bare'"
 
-	# Check if the alias is present in the shell configuration file
-	if ! grep -q "$ALIAS_STRING" "$SHELL_CONFIG"; then
-		sleep 0.05
-		echo -e " ${GRAY}|${RESET} Consider aliasing '${GREEN}bare${RESET}' in your"
-		echo -e " ${GRAY}|${RESET} shell config to access bare wherever you are."
-		echo ""
-		echo -e " ${GRAY}|${RESET} You can run this in your terminal:"
-		echo -e " ${GRAY}|${RESET} echo \"$ALIAS_STRING\" >> $SHELL_CONFIG"
-		echo ""
-		# Prompt the user to add the alias
-		read -rp " ${GRAY}|${RESET} Would you like us to run that for you? (y/n) : " response
-		if [[ $response =~ ^[Yy]$ ]]; then
-			echo "$ALIAS_STRING" >> "$SHELL_CONFIG"
-		fi
-	else
-		echo -e " ${GRAY}|${RESET} ${GREEN}bare${RESET} is aliased for use throughout the terminal. Nice 💪"
-		echo -e " ${GRAY}|${RESET} Restart your shell to run \`${GREEN}bare${RESET}\` or \`${GREEN}bare terminal${RESET}\` from anywhere in your terminal."
-	fi
+    # Check if the alias is present in the shell configuration file
+    if ! grep -q "$ALIAS_STRING" "$SHELL_CONFIG"; then
+        sleep 0.05
+        echo -e " ${GRAY}|${RESET} Consider aliasing '${GREEN}bare${RESET}' in your"
+        echo -e " ${GRAY}|${RESET} shell config to access bare wherever you are."
+        echo ""
+        echo -e " ${GRAY}|${RESET} You can run this in your terminal:"
+        echo -e " ${GRAY}|${RESET} echo \"$ALIAS_STRING\" >> $SHELL_CONFIG"
+        echo ""
+        # Prompt the user to add the alias
+        read -rp " ${GRAY}|${RESET} Would you like us to run that for you? (y/n) : " response
+        if [[ $response =~ ^[Yy]$ ]]; then
+            echo "$ALIAS_STRING" >> "$SHELL_CONFIG"
+        fi
+    else
+        echo -e " ${GRAY}|${RESET} ${GREEN}bare${RESET} is aliased for use throughout the terminal. Nice 💪"
+        echo -e " ${GRAY}|${RESET} Restart your shell to run \`${GREEN}bare${RESET}\` or \`${GREEN}bare terminal${RESET}\` from anywhere in your terminal."
+    fi
 
-	echo ""
-	echo -e " ${GRAY}|${RESET} ${BLUE}Go conquer the world with ${GREEN}bare${RESET}."
-	echo ""
-	sleep 0.05
+    echo ""
+    echo -e " ${GRAY}|${RESET} ${BLUE}Go conquer the world with ${GREEN}bare${RESET}."
+    echo ""
+    sleep 0.05
 }
 
 # Run setup
diff --git a/date b/date
--- a/date
+++ b/date
@@ -3,129 +3,87 @@
 # Capture input if piped
 [[ -t 0 ]] || input=$(cat)
 
+# set system timezone temporarily
+TZ="$BARE_TIMEZONE"
+
+# Determine the correct date command based on the operating system
+if [[ "$OS" == "macOS" ]]; then
+    DATE_CMD="gdate"
+else
+    DATE_CMD="date"
+fi
+
 # Initialize empty array for remaining arguments
 remaining_args=()
 
 date_format="%Y-%m-%d %H:%M:%S"
 input_format="%Y-%m-%d %H:%M:%S"
+offset=""
 
 # Process arguments
 while [[ $# -gt 0 ]]; do
   case $1 in
-    -F|--format|--formatted)
+    as|-F|--format|--formatted) # can't do -f here since native date relies on this
         custom_format=1 && shift
-        case $1 in
-			"mm-dd-yyyy"|"mm-dd-Y") date_format="%m-%d-%Y" ;;
-			"mm/dd/yyyy"|"mm/dd/Y") date_format="%m/%d/%Y" ;;
-			"mm.dd.yyyy"|"mm.dd.Y") date_format="%m.%d.%Y" ;;
-			"dd-mm-yyyy"|"dd-mm-Y") date_format="%d-%m-%Y" ;;
-			"dd/mm/yyyy"|"dd/mm/Y") date_format="%d/%m/%Y" ;;
-			"dd.mm.yyyy"|"dd.mm.Y") date_format="%d.%m.%Y" ;;
-			"yyyy-mm-dd"|"Y-mm-dd") date_format="%Y-%m-%d" ;;
-			"yyyy/mm/dd"|"Y/mm/dd") date_format="%Y/%m/%d" ;;
-			"yyyy.mm.dd"|"Y.mm.dd") date_format="%Y.%m.%d" ;;
-			"yyyy-mm-ddThh:mm:ss"|"Y-mm-ddThh:mm:ss") date_format="%Y-%m-%dT%H:%M:%S" ;;
-			"yyyy-mm-ddThh:mm:ssZ"|"Y-mm-ddThh:mm:ssZ") date_format="%Y-%m-%dT%H:%M:%SZ" ;;
-			"yyyy-mm-dd hh:mm"|"Y-mm-dd hh:mm") date_format="%Y-%m-%d %H:%M" ;;
-			"yyyy-mm-dd h:mm"|"Y-mm-dd h:mm") date_format="%Y-%m-%d %-H:%M" ;;
-			"yyyy-mm-dd hh:mm am/pm"|"Y-mm-dd hh:mm am/pm"|"Y-m-d hh:mm am/pm") date_format="%Y-%m-%d %I:%M %p" ;;
-			"yyyy-mm-dd h:mm am/pm"|"Y-mm-dd h:mm am/pm") date_format="%Y-%m-%d %-l:%M %p" ;;
-			"yyyy-mm-dd hh:mm:ss"|"Y-mm-dd hh:mm:ss") date_format="%Y-%m-%d %H:%M:%S" ;;
-			"yyyy-mm-dd h:mm:ss"|"Y-mm-dd h:mm:ss") date_format="%Y-%m-%d %-H:%M:%S" ;;
-			"mm-dd-yyyy hh:mm:ss"|"mm-dd-Y hh:mm:ss") date_format="%m-%d-%Y %H:%M:%S" ;;
-			"mm-dd-yyyy h:mm:ss"|"mm-dd-Y h:mm:ss") date_format="%m-%d-%Y %-H:%M:%S" ;;
-			"mm/dd/yyyy hh:mm:ss"|"mm/dd/Y hh:mm:ss") date_format="%m/%d/%Y %H:%M:%S" ;;
-			"mm/dd/yyyy h:mm:ss"|"mm/dd/Y h:mm:ss") date_format="%m/%d/%Y %-H:%M:%S" ;;
-			"dd-mm-yyyy hh:mm:ss"|"dd-mm-Y hh:mm:ss") date_format="%d-%m-%Y %H:%M:%S" ;;
-			"dd-mm-yyyy h:mm:ss"|"dd-mm-Y h:mm:ss") date_format="%d-%m-%Y %-H:%M:%S" ;;
-			"dd/mm/yyyy hh:mm:ss"|"dd/mm/Y hh:mm:ss") date_format="%d/%m/%Y %H:%M:%S" ;;
-			"dd/mm/yyyy h:mm:ss"|"dd/mm/Y h:mm:ss") date_format="%d/%m/%Y %-H:%M:%S" ;;
-			"mm/dd/yyyy hh:mm am/pm"|"mm/dd/Y hh:mm am/pm") date_format="%m/%d/%Y %I:%M %p" ;;
-			"mm/dd/yyyy h:mm am/pm"|"mm/dd/Y h:mm am/pm") date_format="%m/%d/%Y %-l:%M %p" ;;
-			"m/d/yyyy"|"m/d/Y") date_format="%-m/%-d/%Y" ;;
-			"m/d/yyyy hh:mm am/pm"|"m/d/Y hh:mm am/pm") date_format="%-m/%-d/%Y %I:%M %p" ;;
-			"m/d/yyyy h:mm am/pm"|"m/d/Y h:mm am/pm") date_format="%-m/%-d/%Y %-l:%M %p" ;;
-			"m/d/yyyy hh:mm:ss"|"m/d/Y hh:mm:ss") date_format="%-m/%-d/%Y %H:%M:%S" ;;
-			"m/d/yyyy h:mm:ss"|"m/d/Y h:mm:ss") date_format="%-m/%-d/%Y %-H:%M:%S" ;;
-			"yyyy-mm-dd hh:mm:ss Z"|"Y-mm-dd hh:mm:ss Z") date_format="%Y-%m-%d %H:%M:%S %z" ;;
-			"yyyy-mm-dd h:mm:ss Z"|"Y-mm-dd h:mm:ss Z") date_format="%Y-%m-%d %-H:%M:%S %z" ;;
-			"yyyy-mm-ddThh:mm:ss+hh:mm"|"Y-mm-ddThh:mm:ss+hh:mm") date_format="%Y-%m-%dT%H:%M:%S%z" ;;
-			"yyyy-mm-dd hh:mm:ss z"|"Y-mm-dd hh:mm:ss z") date_format="%Y-%m-%d %H:%M:%S %Z" ;;
-			"yyyy-mm-dd h:mm:ss z"|"Y-mm-dd h:mm:ss z") date_format="%Y-%m-%d %-H:%M:%S %Z" ;;
-			"yyyy/mm/dd hh:mm:ss Z"|"Y/mm/dd hh:mm:ss Z") date_format="%Y/%m/%d %H:%M:%S %z" ;;
-			"yyyy/mm/dd h:mm:ss Z"|"Y/mm/dd h:mm:ss Z") date_format="%Y/%m/%d %-H:%M:%S %z" ;;
-			"yyyy.mm.dd hh:mm:ss Z"|"Y.mm.dd hh:mm:ss Z") date_format="%Y.%m.%d %H:%M:%S %z" ;;
-			"yyyy.mm.dd h:mm:ss Z"|"Y.mm.dd h:mm:ss Z") date_format="%Y.%m.%d %-H:%M:%S %z" ;;
-			"dd.mm.yyyy hh:mm:ss"|"dd.mm.Y hh:mm:ss") date_format="%d.%m.%Y %H:%M:%S" ;;
-			"dd.mm.yyyy h:mm:ss"|"dd.mm.Y h:mm:ss") date_format="%d.%m.%Y %-H:%M:%S" ;;
-			"dd/mm/yyyy hh:mm:ss Z"|"dd/mm/Y hh:mm:ss Z") date_format="%d/%m/%Y %H:%M:%S %z" ;;
-			"dd/mm/yyyy h:mm:ss Z"|"dd/mm/Y h:mm:ss Z") date_format="%d/%m/%Y %-H:%M:%S %z" ;;
-			"yy/mm/dd"|"y/m/d") date_format="%y/%m/%d" ;;
-			"yy-mm-dd"|"y-m-d") date_format="%y-%m-%d" ;;
-			"dd/mm/yy"|"d/m/y") date_format="%d/%m/%y" ;;
-			"mm/dd/yy"|"m/d/y") date_format="%m/%d/%y" ;;
-			"m/d/yy"|"m/d/y") date_format="%-m/%-d/%y" ;;
-			"yyyy-Www-d"|"Y-Www-d") date_format="%G-W%V-%u" ;;
-			"yyyy-ww"|"Y-ww") date_format="%G-%V" ;;
-			"yyyy-ww-d"|"Y-ww-d") date_format="%G-%V-%u" ;;
-			"yyyy-mm-dd (ddd)"|"Y-mm-dd (ddd)") date_format="%Y-%m-%d (%a)" ;;
-			"ddd, yyyy-mm-dd"|"ddd, Y-mm-dd") date_format="%a, %Y-%m-%d" ;;
-			"ddd mm/dd/yyyy"|"ddd mm/dd/Y") date_format="%a %m/%d/%Y" ;;
-			"hh:mm:ss") date_format="%H:%M:%S" ;;
-			"h:mm:ss") date_format="%-H:%M:%S" ;;
-			"hh:mm") date_format="%H:%M" ;;
-			"h:mm") date_format="%-H:%M" ;;
-			"hh:mm am/pm") date_format="%I:%M %p" ;;
-			"h:mm am/pm") date_format="%-l:%M %p" ;;
-			"hh:mm:ss.SSS") date_format="%H:%M:%S.%3N" ;;
-			"hh:mm:ss.SSS am/pm") date_format="%I:%M:%S.%3N %p" ;;
-			"hh:mm:ss TZD") date_format="%H:%M:%S %Z" ;;
-			"hh:mm:ss z") date_format="%H:%M:%S %z" ;;
-			"yyyyMMdd"|"YMMdd") date_format="%Y%m%d" ;;
-			"MMddyyyy"|"Mdyyyy") date_format="%m%d%Y" ;;
-			"ddMMyyyy"|"dMyyyy") date_format="%d%m%Y" ;;
-			"yyyyMMddHHmmss"|"YMMddHHmmss") date_format="%Y%m%d%H%M%S" ;;
-			"MMddyyyyHHmmss"|"MdyyyyHHmmss") date_format="%m%d%Y%H%M%S" ;;
-			"ddMMyyyyHHmmss"|"dMyyyyHHmmss") date_format="%d%m%Y%H%M%S" ;;
-			*) echo "Invalid format" && exit 1 ;;
-		esac
+        read -r -a format_parts <<< "$1"  # Allows us to handle date and time dynamically as parts
+        date_format=""
+        for part in "${format_parts[@]}"; do
+            case $part in
 
+                'U') date_format+="%s " ;;  # 1628841600
 
+                'Y-M-D') date_format+="%Y-%m-%d " ;;  # 2024-08-13
+                'M-D-Y') date_format+="%m-%d-%Y " ;;  # 08-13-2024
+                'M/D/Y') date_format+="%m/%d/%Y " ;;  # 08/13/2024
+
+                # Additional formats to handle leading zeroes
+                'Y-m-d') date_format+="%Y-%-m-%-d " ;;  # 2024-8-13
+                'y-m-d') date_format+="%y-%-m-%-d " ;;  # 24-8-13
+                'd-m-Y') date_format+="%-d-%-m-%Y " ;;  # 13-8-2024
+                'm-d-Y') date_format+="%-m-%-d-%Y " ;;  # 8-13-2024
+                'd/m/Y') date_format+="%-d/%-m/%Y " ;;  # 13/8/2024
+                'm/d/Y') date_format+="%-m/%-d/%Y " ;;  # 8/13/2024
+
+                # times
+                'H:M:S'|'H:m:s') date_format+="%H:%M:%S " ;; # 14:30:00
+                'H:M'|'H:m') date_format+="%H:%M " ;; # 14:30
+                'h:m:s'|'h:M:S'|'h:M:s'|'h:m:S') date_format+="%-I:%M:%S %p " ;; # 2:30:00 PM
+                'h:m'|'h:M') date_format+="%-I:%M %p " ;; # 2:30 PM
+
+                *) echo "Invalid format" && exit 1 ;;
+
+            esac
+        done
+        date_format="${date_format% }"  # Remove trailing space
+        shift
+        ;;
+    --offset)
+        shift
+        offset="$1"
         shift
         ;;
     *)
         remaining_args+=("$1")
+        shift
         ;;
   esac
-  shift
 done
 
 # Set the remaining arguments
 set -- "${remaining_args[@]}"
 
 # If no arguments or input, default to today's date
-[[ -z $input && $# -eq 0 ]] && input=$(gdate +"%Y-%m-%d %H:%M:%S")
+[[ -z $input && $# -eq 0 ]] && input=$(TZ=$TZ gdate +"%Y-%m-%d %H:%M:%S")
 [[ -z $input ]] && input="$1"
 
-
 # Detect the operating system
 os_type=$(uname)
 
 # Get today's date in yyyy-mm-dd format
 if [ "$os_type" = "Darwin" ] && command -v gdate &> /dev/null; then
-    today=$(gdate +"%Y-%m-%d")
+    today=$(TZ=$TZ gdate +"%Y-%m-%d")
 else
-    today=$(date +"%Y-%m-%d")
-fi
-
-# Detect the operating system
-os_type=$(uname)
-
-# Get today's date in yyyy-mm-dd format
-if [ "$os_type" = "Darwin" ] && command -v gdate &> /dev/null; then
-    today=$(gdate +"%Y-%m-%d")
-else
-    today=$(date +"%Y-%m-%d")
+    today=$(TZ=$TZ date +"%Y-%m-%d")
 fi
 
 # condition yyyy-mm-dd
@@ -144,32 +102,28 @@ elif [[ $(validate date "$input" --format 'hh:mm') == 'true' ]]; then
 # hh:mm:ss
 elif [[ $(validate date "$input" --format 'hh:mm:ss') == 'true' ]]; then
     input="$today $input"
+# yyyy-mm-ddThh:mm:ssZ
+elif [[ $(validate date "$input" --format 'Y-m-d\Thh:mm:ss\Z') == 'true' ]]; then
+    :
 fi
 
 # Validate the date and time
-os_type=$(uname)
 if [[ $# -eq 1 ]]; then
-  if [ "$os_type" = "Darwin" ]; then
-    # macOS date validation
-    gdate -d "$input_format" "$input" &> /dev/null && valid_date="true"
-  elif [ "$os_type" = "Linux" ]; then
-    # Linux date validation
-    gdate -d "$input" &> /dev/null && valid_date="true"
-  fi
+    if [ "$OS" = "macOS" ]; then
+        gdate -d "$input_format" "$input" &> /dev/null && valid_date="true"
+    else
+        gdate -d "$input" &> /dev/null && valid_date="true"
+    fi
 fi
 
 # Format and print the date using the specified format, or default to standard
 if [[ $custom_format == 1 ]]; then
-    # Detect the operating system
-    if [[ "$os_type" == "Darwin" ]]; then
-        # macOS
-        formatted_date=$(gdate -d "$input" +"$date_format")
+    if [[ "$OS" == "macOS" ]]; then
+        formatted_date=$(TZ=$TZ gdate -d "$input" +"$date_format")
     else
-        # Assume Linux (Ubuntu)
-        formatted_date=$(gdate -d "$input" +"$date_format")
+        formatted_date=$(TZ=$TZ gdate -d "$input" +"$date_format")
     fi
-    
     echo "$formatted_date" && exit 0
 else
-    /bin/date "$@"
+    TZ=$TZ /bin/date "$@"
 fi
diff --git a/random b/random
--- a/random
+++ b/random
@@ -1,14 +1,34 @@
 #!/usr/bin/env bash
 
-# Get the command and length
-command=$1
-length=${2:-16}
+function main() {
+	# Default command
+	local command='string'
+	local length='16'
+	local constraint=''
+	# Parse arguments
+	while [[ $# -gt 0 ]]; do
+		case $1 in
+			string|alpha|number) command=$1 ;;
+			*) length=$1 ;;
+		esac && shift
+	done
 
-[[ ! $length =~ ^[0-9]+$ ]] && echo "Invalid length: $length. Must be a positive integer." && exit 1;
+	# Validate the length
+	if [[ ! $length =~ ^[0-9]+$ ]]; then
+		echo "Invalid length: $length. Must be a positive integer."
+		exit 1
+	fi
 
-case $command in
-	string ) LC_ALL=C tr -dc 'a-zA-Z0-9' < /dev/urandom | head -c "$length"; echo ;;
-	alpha ) LC_ALL=C tr -dc 'a-zA-Z' < /dev/urandom | head -c "$length"; echo ;;
-	number ) LC_ALL=C tr -dc '0-9' < /dev/urandom | head -c "$length"; echo ;;
-	* ) echo "Invalid command: $command" && exit 1 ;;
-esac
+	# Character sets for each command
+	case $command in
+		string) constraint='a-zA-Z0-9' ;;
+		alpha) constraint='a-zA-Z' ;;
+		number) constraint='0-9' ;;
+		*) echo "Invalid command: $command" && exit 1 ;;
+	esac
+
+	# Generate random string
+	LC_ALL=C tr -dc "$constraint" < /dev/urandom | head -c "$length"; echo
+}
+
+run_script "$@"
